name: Build/release

on: push

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        #run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run dist build
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release
        if: startsWith(github.ref, 'refs/tags/') == true
