name: Build/release

on: push

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build Linux
        if: runner.os == "linux"
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release_linux
      - name: Build Windows
        if: runner.os == "windows"
        run: $env:${{ secrets.GITHUB_TOKEN }} npm run release_win
