name: Build/release

on: push

jobs:
  release_linux:
    name: Release Linux
    if: startsWith(github.ref, 'refs/tags/') == true
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build Windows
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release-linux
        
  release_win:
    name: Release Windows
    if: startsWith(github.ref, 'refs/tags/') == true
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build Linux
        run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run release-win
