name: Build/release

on: push

jobs:
  release:
    runs-on: [ubuntu-lates]
    steps:
    - name: Electron Forge Action
      uses: yinxulai/actions-electron-forge@0.05
      with:
        # GitHub authentication token
        # github_token: 
        # Directory where NPM/Yarn commands should be run
        package_root: # optional, default is .
        # Optional package.json scripts name
        script_name: # optional, default is publish
        # Whether the app should be released after a successful build
        release: # optional
